#!/bin/sh

SCRIPT=`readlink -f $0`

DIR_HOME=`dirname $SCRIPT`
echo "HOME: $DIR_HOME"

LIB_SYSROOT="$SYSROOT/lib"
LIB_TIZEN="$SYSROOT/usr/lib"
LIB_OSP="$SYSROOT/usr/lib/osp"

export PATH="$PATH:$TIZEN_HOME/tools/i386-linux-gnueabi-gcc-4.5/bin"
echo "Tizne Header: $INC_TIZEN"
echo "OSP Header: $INC_OSP"
echo "OSP Lib: $OSP_LIB"

if [ -z "$1" ]
then
	echo "Specify target"
fi

MANIFEST=$1
TARGET=$1/target

#cd ./Debug-Tizen-Emulator


echo "i386-linux-gnueabi-g++ PATH: $(which i386-linux-gnueabi-g++)"

SRC_LIST=`find src -name *.cpp`

O_LIST=""

for SRC_NAME in $SRC_LIST
do
	D_NAME="${SRC_NAME%.*}.d"
	O_NAME="${SRC_NAME%.*}.o"

	O_LIST="$O_LIST $O_NAME"

	i386-linux-gnueabi-g++ -I"pch" -DNODE_STATIC -D_DEBUG -I"$DIR_HOME/inc" -O0 -g3 -Wall -c -fmessage-length=0 -fPIE -I"$INC_TIZEN" -I"$INC_XML" -I"$TIZEN_HOME/library" -I"$INC_OSP" --sysroot="$SYSROOT" -D_APP_LOG -MMD -MP -MF"$D_NAME" -MT"$D_NAME" -o "$O_NAME" "$SRC_NAME"

done;

mkdir -p "$TARGET/bin"

cp $LIB_NODE $DIR_HOME/lib/libnode.so
echo "Linking..."
i386-linux-gnueabi-g++ -o"$TARGET/cantata.exe" $O_LIST -L"$DIR_HOME/lib" -Xlinker --as-needed -pie -lpthread -Xlinker -rpath=\$ORIGIN/../lib --sysroot="$SYSROOT" -L"$LIB_TIZEN" -L"$LIB_OSP" -losp-appfw -losp-uifw -losp-image -losp-json -losp-ime -losp-net -lpthread -losp-content -losp-locations -losp-telephony -losp-uix -losp-media -losp-messaging -losp-web -losp-social -losp-wifi -losp-bluetooth -losp-nfc -losp-face -losp-speech-tts -losp-speech-stt -losp-shell -losp-shell-core -lxml2 -losp-vision -ldl -lnode

echo "cp $DIR_HOME/manifest.xml $MANIFEST"
cp $DIR_HOME/manifest.xml $MANIFEST
mkdir -p $DIR_HOME/res
cp -R $DIR_HOME/res $MANIFEST
mkdir -p $DIR_HOME/lib
cp -R $DIR_HOME/lib $MANIFEST
mkdir -p $DIR_HOME/icons
cp -R $DIR_HOME/icons $MANIFEST
mkdir -p $DIR_HOME/data
cp -R $DIR_HOME/data $MANIFEST

