#!/bin/sh

SCRIPT=`readlink -f $0`

DIR_HOME=`dirname $SCRIPT`
echo "HOME: $DIR_HOME"

TIZEN_HOME="/home/bylee/tizen_sdk"
SYSROOT="$TIZEN_HOME/platforms/tizen2.1/rootstraps/tizen-emulator-2.1.native"
SYSROOT_LIB="$SYSROOT/lib"
TIZEN_INC="$SYSROOT/usr/include"
TIZEN_LIB="$SYSROOT/usr/lib"
XML_INC="$TIZEN_INC/libxml2"
OSP_INC="$TIZEN_INC/osp"
OSP_LIB="$SYSROOT/usr/lib/osp"

export PATH="$PATH:$TIZEN_HOME/tools/i386-linux-gnueabi-gcc-4.5/bin"
echo "Tizne Header: $TIZEN_INC"
echo "OSP Header: $OSP_INC"
echo "OSP Lib: $OSP_LIB"

MANIFEST=$DIR_HOME
TARGET=$DIR_HOME/bin
if [ -n "$1" ]
then
	MANIFEST=$1
    TARGET=$1/target
fi

#cd ./Debug-Tizen-Emulator


echo "i386-linux-gnueabi-g++ PATH: $(which i386-linux-gnueabi-g++)"

SRC_LIST=`find src -name *.cpp`

O_LIST=""

for SRC_NAME in $SRC_LIST
do
	D_NAME="${SRC_NAME%.*}.d"
	O_NAME="${SRC_NAME%.*}.o"

	O_LIST="$O_LIST $O_NAME"

	i386-linux-gnueabi-g++ -I"pch" -D_DEBUG -I"$DIR_HOME/inc" -O0 -g3 -Wall -c -fmessage-length=0 -fPIE -I"$TIZEN_INC" -I"$XML_INC" -I"$TIZEN_HOME/library" -I"$OSP_INC" -D_APP_LOG -MMD -MP -MF"$D_NAME" -MT"$D_NAME" -o "$O_NAME" "$SRC_NAME"

done;

mkdir -p "$TARGET/bin"

i386-linux-gnueabi-g++ -o"$TARGET/cantata.exe" $O_LIST -L"$DIR_HOME/lib" -Xlinker --as-needed -pie -lpthread -Xlinker -rpath=\$ORIGIN/../lib --sysroot="$SYSROOT" -L"$TIZEN_LIB" -L"$OSP_LIB" -losp-appfw -losp-uifw -losp-image -losp-json -losp-ime -losp-net -lpthread -losp-content -losp-locations -losp-telephony -losp-uix -losp-media -losp-messaging -losp-web -losp-social -losp-wifi -losp-bluetooth -losp-nfc -losp-face -losp-speech-tts -losp-speech-stt -losp-shell -losp-shell-core -lxml2 -losp-vision -ldl

cp $DIR_HOME/manifest.xml $MANIFEST
cp -R $DIR_HOME/res $MANIFEST
cp -R $DIR_HOME/lib $MANIFEST
cp -R $DIR_HOME/icons $MANIFEST
cp -R $DIR_HOME/data $MANIFEST

cd ../
echo "Finished building target: cantata.exe"
echo "**** Build Finished ****"

